Repository esmero/format_strawberryfield, pull requests merged in 2019-10, with the labels that each got.

#19 ISSUE 18: Use general IIIF settings in Field Formatter default settings
  config/install/format_strawberryfield.iiif_settings.yml
  config/schema/format_strawberryfield.schema.yml
  format_strawberryfield.routing.yml
  src/Form/IiifSettingsForm.php
  src/Plugin/Field/FieldFormatter/Strawberry3DFormatter.php
  src/Plugin/Field/FieldFormatter/StrawberryAudioFormatter.php
  src/Plugin/Field/FieldFormatter/StrawberryBaseFormatter.php
  src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
  src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
  src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
  src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
  src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
  src/Plugin/Field/FieldFormatter/StrawberryVideoFormatter.php
  src/Tools/IiifHelper.php
  src/Tools/IiifUrlValidator.php
Labels: enhancement, good first issue

#29 ISSUE-18b: Fix Broken IIIF Formatters after ISSUE-18 refactor
  .gitignore
  src/Form/IiifSettingsForm.php
  src/Plugin/Field/FieldFormatter/StrawberryBaseFormatter.php
  src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
  src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
  src/Tools/IiifHelper.php
  src/Tools/IiifUrlValidator.php
Labels: bug

#31 ISSUE-22: Fix left overs from first ISSUE-22 pull (Number 27)
  format_strawberryfield.routing.yml
  src/Entity/MetadataExposeConfigEntity.php
  src/Form/MetadataExposeConfigEntityDeleteForm.php
Labels: bug, enhancement

#32 ISSUE-22: Fix Routing issues and Active/inactive, Gives the Config Entity some Love
  format_strawberryfield.routing.yml
  src/Controller/MetadataExposeDisplayController.php
  src/Entity/Controller/MetadataExposeConfigEntityListBuilder.php
  src/Form/MetadataExposeConfigEntityForm.php
Labels: bug, enhancement
