Repository esmero/format_strawberryfield, pull requests merged in 2022-11, with the labels that each got.

#239 ISSUE-237: bad indentation for UV formatter schema
  config/schema/format_strawberryfield.schema.yml
Labels: bug

#240 ISSUE-236: Citation Formatter check for null
  src/Plugin/Field/FieldFormatter/StrawberryCitationFormatter.php
Labels: bug

#243 ISSUE-241: Citation Formatter settings undefined variables
  src/Plugin/Field/FieldFormatter/StrawberryCitationFormatter.php
Labels: bug, Field Formatter

#245 ISSUE-244 --- Workaround Mirador to allow mutiple Audios on Chrome/Firefox
  js/mirador_strawberry.js
Labels: enhancement, Javascript, IIIF, UX
